Resolve cran errors
agenius-mohammed-ali/DGEobj.utils pull request #8
Opened 2021-10-19 12:03 UTC by agenius-mohammed-ali

2021-10-19 23:50 UTC, cb4ds requested changes
looks good except for the use of Next

2021-10-19 23:50 UTC, cb4ds commented on R/runIHW.R
> +
rework to remove this logic - instead do something if !is.null(ihwResult).

2021-10-20 05:27 UTC, agenius-mohammed-ali commented on R/runIHW.R
> +
done

2021-10-25 18:27 UTC, cb4ds approved these changes

2021-10-25 20:18 UTC, merged